# BasicInventory is commercial software: buying a licence is how it is funded,
# so there is no donation platform here. Uncomment the store URLs once they are
# live — a "Sponsor" button pointing at a dead link is worse than no button.

# custom:
#   - "https://www.ebay.es/usr/<your-shop>"
#   - "https://<your-account>.gumroad.com/l/basicinventory"
