# BasicInventory is commercial software: buying a licence is how it is funded,
# so the button points at the store rather than at a donation platform.
custom:
  - "https://www.ebay.es/itm/318673321758"
  - "https://xabier6.gumroad.com/l/basicinventory"
