# BasicInventory is commercial software: buying a licence is how it is funded,
# so the button points at the Microsoft Store rather than at a donation platform.
custom:
  - "https://apps.microsoft.com/detail/9N8GQS365ZLM"
